import Head from 'next/head';
import { ChakraProvider, extendTheme } from '@chakra-ui/react';
import { StoreProvider } from 'easy-peasy';
import 'reset-css';

import PlayerLayout from '../components/playerLayout';
import { store } from '../lib/store';

const theme = extendTheme({
  // TODO: for responsive desgin (font-size => 1rm == 10px)
  // styles: {
  //   global: {
  //     html: {
  //       fontSize: '62.5%',
  //     },
  //   },
  // },
  colors: {
    gray: {
      100: '#F5F5F5',
      200: '#EEEEEE',
      300: '#E0E0E0',
      400: '#BDBDBD',
      500: '#9E9E9E',
      600: '#757575',
      700: '#616161',
      800: '#424242',
      900: '#212121',
    },
  },
  components: {
    Button: {
      variants: {
        link: {
          ':foucs': { outline: 'none', boxShadow: 'none' },
        },
      },
    },
  },
});

const MyApp = ({ Component, pageProps }) => {
  return (
    <StoreProvider store={store}>
      <ChakraProvider theme={theme}>
        <Head>
          <title>Tracks</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.svg" />
        </Head>

        {Component.authPage ? (
          <Component {...pageProps} />
        ) : (
          <PlayerLayout>
            <Component {...pageProps} />
          </PlayerLayout>
        )}
      </ChakraProvider>
    </StoreProvider>
  );
};

export default MyApp;
